[project]
name = "capstonellm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.36.9",
    "pyspark>=4.0.1",
    "pytest>=9.0.3",
    "requests>=2.33.0",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
