name: capstone_llm_duckdb
version: "1.0.0"
config-version: 2

profile: capstone_llm_duckdb

model-paths:
  - models

clean-targets:
  - target
  - dbt_packages

vars:
  tag: dbt
  raw_root: local/data/raw

models:
  capstone_llm_duckdb:

    staging:
      +materialized: view

    intermediate:
      +materialized: view

    marts:
      +materialized: table