docker:
    path: .
id: e3a7de2b-8381-4b5b-b14b-79175cda2bee
ide:
    filename: ide.yaml
name: capstonellm-wilsonnietoluna
resources:
    path: resources
streaming:
    filename: streaming.yaml
template: ""
version: "0.3"
workflows:
    path: dags
    version: "3"
